name: CODEX IPv6 Probe
on:
  workflow_dispatch:
    inputs:
      url:
        required: true
        type: string
jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - name: Curl URL
        run: |
          set -euxo pipefail
          curl -g -6 -v --max-time 12 "$URL"
        env:
          URL: ${{ inputs.url }}
